Traceback (most recent call last):
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import dependency

import os
import numpy as np
import pandas as pd
from IPython.display import HTML, display_html

from appstore.container import AppstoreContainer

container = AppstoreContainer()
container.init_resources()
pd.set_option("max_colwidth", 400)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mdependency[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

File [0;32m~/projects/appstore/jbook/3_data/dependency.py:36[0m
[1;32m     33[0m [38;5;28;01mfrom[39;00m [38;5;21;01mappstore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcontainer[39;00m [38;5;28;01mimport[39;00m AppstoreContainer  [38;5;66;03m# noqa[39;00m
[1;32m     35[0m container [38;5;241m=[39m AppstoreContainer()
[0;32m---> 36[0m [43mcontainer[49m[38;5;241;43m.[39;49m[43minit_resources[49m[43m([49m[43m)[49m
[1;32m     37[0m container[38;5;241m.[39mwire(packages[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mappstore[39m[38;5;124m"[39m])

File [0;32msrc/dependency_injector/containers.pyx:343[0m, in [0;36mdependency_injector.containers.DynamicContainer.init_resources[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:3786[0m, in [0;36mdependency_injector.providers.Resource.init[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:225[0m, in [0;36mdependency_injector.providers.Provider.__call__[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:3894[0m, in [0;36mdependency_injector.providers.Resource._provide[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:608[0m, in [0;36mdependency_injector.providers.__call[0;34m()[0m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/logging/config.py:811[0m, in [0;36mdictConfig[0;34m(config)[0m
[1;32m    809[0m [38;5;28;01mdef[39;00m [38;5;21mdictConfig[39m(config):
[1;32m    810[0m [38;5;250m    [39m[38;5;124;03m"""Configure logging using a dictionary."""[39;00m
[0;32m--> 811[0m     [43mdictConfigClass[49m[43m([49m[43mconfig[49m[43m)[49m[38;5;241m.[39mconfigure()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/logging/config.py:375[0m, in [0;36mBaseConfigurator.__init__[0;34m(self, config)[0m
[1;32m    374[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, config):
[0;32m--> 375[0m     [38;5;28mself[39m[38;5;241m.[39mconfig [38;5;241m=[39m [43mConvertingDict[49m[43m([49m[43mconfig[49m[43m)[49m
[1;32m    376[0m     [38;5;28mself[39m[38;5;241m.[39mconfig[38;5;241m.[39mconfigurator [38;5;241m=[39m [38;5;28mself[39m

[0;31mTypeError[0m: 'NoneType' object is not iterable

